#include <iostream>
#include<string>
using namespace std;

int main()
{
	string str1 = "Hello how are you";
	string str2;
	str2 = str1.substr(str1.find("how"),3);
	cout<<str2;
	
//	cout<<len<<endl;
//	cout<<str1;
//	str1.clear();//clear the string it has nothing
//	cout<<str1;
//cout<<str1.front();//H----first character of string
//cout<<str1.back();//u--->last character of string
		//str1.append(" I am fine");//insert string at the last of ist string
		//cout<<str1;
		//push_back()----pop_back()
		//these only insert or remove characters
//		str1.push_back('Z');
//		cout<<str1<<endl;
//		str1.pop_back();//no argument
//		str1.pop_back();//no argument
//		str1.pop_back();//no argument
//		str1.pop_back();//no argument
//		cout<<str1;
//		cout<<str1;
//		cout<<endl;
//		cout<<str2;
//		cout<<endl;
//		cout<<"-----------------\n";
//		str1.swap(str2);
//		cout<<str1;
//		cout<<endl;
//		cout<<str2;
//		cout<<endl;
//		cout<<str1;
//		cout<<endl;
		//str1.erase(str1.begin()+1);
//		str1.erase(2,5);
//		cout<<str1;
//position
//length
//you---->Ali
//str1.replace(14,3,"Ali");
//cout<<str1;

             
             

    
}